### ISSUE TITLE
Change `else` in syntax to `otherwise`, or make both work.

### ISSUE THREAD

**Issue by somerandomdev49** [enact-lang/enact#67]
Because this language is intended to be simple, I think `otherwise` keyword would be better than `else`. Also, for experienced programmers, `else` would be better, so it will be nice to have both `else` and `otherwise`.

so, in the example from README:
```
// FizzBuzz in Enact
each i in 1..20:
    given (i % 3 == 0, i % 5 == 0):
        when (true, true):
            print("FizzBuzz")
        when (true, false):
            print("Fizz")
        when (false, true):
            print("Buzz")
        otherwise:   // <-- this looks better for beginners.
            print(i)
    end
end
```

**Comment by Dandigit** [comment]
The language is intended to be simple, sure, but I don't believe that changing the very familiar `else` keyword to something else, like `otherwise`, is going to achieve this goal.

The familiarity that comes with the `else` keyword far outweighs the readability of the `otherwise` keyword (in my opinion) if Enact is to be as approachable as possible to all programmers.

You do propose keeping both the `else` and `otherwise` keyword to get the best of both worlds, but I feel that this would just add unnecessary complexity and additional reserved symbols to the language when most programmers would prefer the much shorter-to-type `else` keyword.

For these reasons, I won't implement this proposal. Thank you for the suggestion, though, and if you have any others that you believe would be beneficial, please do feel free to contribute them to the discussion.
